// Firebase Configuration - Generated automatically
// DO NOT EDIT THIS FILE - It will be overwritten
import { initializeApp } from 'firebase/app';
import { getDatabase } from 'firebase/database';
import { getAuth } from 'firebase/auth';

export const firebaseConfig = {
  apiKey: "AIzaSyB8Zb4gHvXlTLstm9GMyAGSzaZTRF0hlS4",
  authDomain: "encuest-app.firebaseapp.com",
  databaseURL: "https://encuest-app-default-rtdb.europe-west1.firebasedatabase.app",
  projectId: "encuest-app",
  storageBucket: "encuest-app.firebasestorage.app",
  messagingSenderId: "1031477674976",
  appId: "1:1031477674976:web:1ab746bf68118a6325a185"
};

const app = initializeApp(firebaseConfig);
export const database = getDatabase(app);
export const auth = getAuth(app);
